### ISSUE TITLE
bcrypt dependency fails on AWS Lambda

### ISSUE THREAD

**Issue by nherasiutsin** [glauberportella/password-hash#5]
The AWS Lambda function with both password-hash and password-hash-leo dependencies gets an error when is invoked:
```
{
    "errorType": "Error",
    "errorMessage": "package.json does not exist at /package.json",
    "stack": [
        "Error: package.json does not exist at /package.json",
        "    at Object.exports.find (/var/task/node-functions/lambda/cognito/handleUserMigrationAuthentication.js:37011:15)",
        "    at Object.<anonymous> (/var/task/node-functions/lambda/cognito/handleUserMigrationAuthentication.js:176283:27)",
        "    at Object.<anonymous> (/var/task/node-functions/lambda/cognito/handleUserMigrationAuthentication.js:176516:30)",
        "    at __webpack_require__ (/var/task/node-functions/lambda/cognito/handleUserMigrationAuthentication.js:20:30)",
        "    at Object.<anonymous> (/var/task/node-functions/lambda/cognito/handleUserMigrationAuthentication.js:84834:16)",
        "    at __webpack_require__ (/var/task/node-functions/lambda/cognito/handleUserMigrationAuthentication.js:20:30)",
        "    at Module.exports.__esModule (/var/task/node-functions/lambda/cognito/handleUserMigrationAuthentication.js:85169:21)",
        "    at __webpack_require__ (/var/task/node-functions/lambda/cognito/handleUserMigrationAuthentication.js:20:30)",
        "    at /var/task/node-functions/lambda/cognito/handleUserMigrationAuthentication.js:84:18",
        "    at Object.<anonymous> (/var/task/node-functions/lambda/cognito/handleUserMigrationAuthentication.js:87:10)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Module.require (internal/modules/cjs/loader.js:692:17)"
    ]
}
```

After some debugging, I could fix an issue with replacing bcrypt dependency with [bcryptjs](https://www.npmjs.com/package/bcryptjs). The reason why it helped is bcrypt uses OS functions that don't exist for a Lambda environment. The bcrypjs on the other hand doesn't require that but it's a little bit slower.  So eventually I have to use the raw source file with that workaround. I know bcrypt was updated to 5.0.0 version but that didn't help. Also, I couldn't reproduce the issue locally.

**Comment by glauberportella** [comment]
Bcryptjs was added to the project and removed the bcrypt as fixed by @nherasiutsin.

**Comment by meirkeller** [comment]
@glauberportella Are you going to release a new version soon with this fix?
